### ISSUE TITLE
Failed to create 4.17.0-rc.1 bundle

### ISSUE THREAD

**Issue by lilyLuLiu** [crc-org/snc#954] opened 2024-09-03 09:45 UTC
./openshift-clients/linux/oc adm release info -a /home/ec2-user/pullsecret [quay.io/crcont/ocp-release:4.17.0-rc.1-amd64](http://quay.io/crcont/ocp-release:4.17.0-rc.1-amd64) --image-for=baremetal-runtimecfg
+ BAREMETAL_RUNTIMECFG=[quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:4410ff4cbd9ff5bbe783a7fd5bf1c5f078e60ae89838bb327790c37c9a71a5f4](http://quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:4410ff4cbd9ff5bbe783a7fd5bf1c5f078e60ae89838bb327790c37c9a71a5f4)
+ ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i id_ecdsa_crc core@api.crc.testing -- ‘sudo podman create --name baremetal_runtimecfg [quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:4410ff4cbd9ff5bbe783a7fd5bf1c5f078e60ae89838bb327790c37c9a71a5f4](http://quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:4410ff4cbd9ff5bbe783a7fd5bf1c5f078e60ae89838bb327790c37c9a71a5f4)’
Warning: Permanently added ‘api.crc.testing’ (ED25519) to the list of known hosts.
Trying to pull [quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:4410ff4cbd9ff5bbe783a7fd5bf1c5f078e60ae89838bb327790c37c9a71a5f4](http://quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:4410ff4cbd9ff5bbe783a7fd5bf1c5f078e60ae89838bb327790c37c9a71a5f4)...
Error: initializing source docker://quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:4410ff4cbd9ff5bbe783a7fd5bf1c5f078e60ae89838bb327790c37c9a71a5f4: reading manifest sha256:4410ff4cbd9ff5bbe783a7fd5bf1c5f078e60ae89838bb327790c37c9a71a5f4 in [quay.io/openshift-release-dev/ocp-v4.0-art-dev](http://quay.io/openshift-release-dev/ocp-v4.0-art-dev): unauthorized: access to the requested resource is not authorized

**Comment by praveenkumar** [comment] 2024-09-20 09:56
Closing this since it is not reproducible, will create new or reopen it if occur again.

**Closed by praveenkumar** 2024-09-20 09:56 UTC
